

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author junior
 */
public class TelaLogin extends javax.swing.JFrame {

    int xMouse;
    int yMouse;
    
    public TelaLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CloseB = new javax.swing.JLabel();
        LblImagem = new javax.swing.JLabel();
        LblNome = new javax.swing.JLabel();
        LblSenha = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        TextField = new javax.swing.JTextField();
        BtnInicio = new javax.swing.JButton();
        TelaArrasto = new javax.swing.JLabel();
        BackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CloseB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseBMouseClicked(evt);
            }
        });
        getContentPane().add(CloseB, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 3, 15, 15));

        LblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user.png"))); // NOI18N
        getContentPane().add(LblImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 250, -1));

        LblNome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LblNome.setForeground(new java.awt.Color(255, 255, 255));
        LblNome.setText("Nome:");
        getContentPane().add(LblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 100, 40));

        LblSenha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LblSenha.setForeground(new java.awt.Color(255, 255, 255));
        LblSenha.setText("Senha:");
        getContentPane().add(LblSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 100, 40));

        PasswordField.setBackground(new java.awt.Color(102, 102, 102));
        PasswordField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PasswordField.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, 210, 20));

        TextField.setBackground(new java.awt.Color(102, 102, 102));
        TextField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TextField.setForeground(new java.awt.Color(255, 255, 255));
        TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(TextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 210, 20));

        BtnInicio.setBackground(new java.awt.Color(153, 153, 153));
        BtnInicio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnInicio.setText("Inicio");
        getContentPane().add(BtnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 560, -1, -1));

        TelaArrasto.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                TelaArrastoMouseDragged(evt);
            }
        });
        TelaArrasto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TelaArrastoMousePressed(evt);
            }
        });
        getContentPane().add(TelaArrasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 20));

        BackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Background.png"))); // NOI18N
        getContentPane().add(BackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseBMouseClicked

    private void TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldActionPerformed

    private void TelaArrastoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TelaArrastoMouseDragged
        int x   =   evt.getXOnScreen();
        int y   =   evt.getYOnScreen();
        
        this.setLocation(x  -   xMouse, y   -   yMouse);
    }//GEN-LAST:event_TelaArrastoMouseDragged

    private void TelaArrastoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TelaArrastoMousePressed

        xMouse  =   evt.getX();
        yMouse  =   evt.getY();
        
    }//GEN-LAST:event_TelaArrastoMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGround;
    private javax.swing.JButton BtnInicio;
    private javax.swing.JLabel CloseB;
    private javax.swing.JLabel LblImagem;
    private javax.swing.JLabel LblNome;
    private javax.swing.JLabel LblSenha;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel TelaArrasto;
    private javax.swing.JTextField TextField;
    // End of variables declaration//GEN-END:variables
}
